### ISSUE TITLE
Is it production ready yet ?

### ISSUE THREAD

**Issue by corporatepiyush** [Gozala/reflex#41]
I came across this framework while searching for FRP JS frameworks such as Cycle.js, Mercury.js etc.
Just wanted to know is this library production ready yet ? Does it have all features of elm-lang ?
If it is not complete, would there be any breaking changes in upcoming version ?

**Comment by corporatepiyush** [comment]
is this project alive ?

**Comment by Gozala** [comment]
Hi @corporatepiyush, this project is alive & mainly being used & tailored for https://github.com/mozilla/browser.html

I would not call it production ready as we have not invested time in unit testing or made sure that it's fully functional across all browsers.

There are also likely to be some breaking changes given that it follows elm architecture that is itself moving target. It also definitely does not have all the elm language features neither it is possible to have them in JS. Flow type checker is nowhere close to provide safety of elm compiler, it is likely to improve over time but with very mutable JS it's never going to be able to make same guarantees as elm. What this library provides is all the building blocks necessary to build web apps in [elm architecture](https://github.com/evancz/elm-architecture-tutorial).

Regards

**Comment by corporatepiyush** [comment]
Thanks Gozala
